[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  port = 8890
  staticServerPort = 3998
  functionsPort = 9001

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SQUARE_ENVIRONMENT,SQUARE_WEBHOOK_SIGNATURE_KEY"

[functions]
  node_bundler = "esbuild"

[functions.send-reminders]
  schedule = "@hourly"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
